# Generated by Django 3.2.8 on 2021-11-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211106_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title_url',
        ),
    ]
