# Generated by Django 3.2.8 on 2021-11-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poject',
            new_name='Project',
        ),
    ]
